[book]
authors = ["WhatIf Editor"]
language = "en"
src = "src"
title = "WhatIf Writer's Room"

[output.html]
# Forces the site to stay in Coal (Dark Mode) on Load
default-theme = "coal"
# CSS tweaks
additional-css = ["theme/custom.css"]

[output.html.search]
# Keeps search bar active
enable = true
